# Generated by Django 5.0.6 on 2024-06-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
